[book]
title = "Django Custom Admin"
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor]

[output]

[output.html]
git-repository-url = "https://github.com/Innova-Group-LLC/custom_admin"
